/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.53
 * Generated at: 2018-10-19 12:23:35 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import moviedam.board.ArticleDBBean;
import moviedam.board.ArticleDataBean;
import java.util.ArrayList;
import java.text.SimpleDateFormat;
import moviedam.board.RestaurantDBBean;
import moviedam.board.RestaurantDataBean;

public final class main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("moviedam.board.RestaurantDataBean");
    _jspx_imports_classes.add("moviedam.board.RestaurantDBBean");
    _jspx_imports_classes.add("moviedam.board.ArticleDataBean");
    _jspx_imports_classes.add("java.text.SimpleDateFormat");
    _jspx_imports_classes.add("moviedam.board.ArticleDBBean");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");

	request.setCharacterEncoding("utf-8");
	String title = "영화담";

      out.write('\n');

	ArrayList<ArticleDataBean> articleList = null; 
	ArticleDBBean article_db = ArticleDBBean.getInstance();
	articleList = article_db.getTopArticles(); 
	
	ArrayList<RestaurantDataBean> article_restaurantList = null; 
	RestaurantDBBean restaurant_db = RestaurantDBBean.getInstance();

      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/module/header.jsp" + "?" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("title", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode(String.valueOf(title ), request.getCharacterEncoding()), out, false);
      out.write('\n');
      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/module/nav.jsp", out, false);
      out.write("\n");
      out.write("\n");
      out.write("<!-- ***** Welcome Area Start ***** -->\n");
      out.write("<section class=\"dorne-welcome-area bg-img bg-overlay\"style=\"background-image: url(/movie-dam/assets/img/bg-img/coverlg_home.jpg);\">\n");
      out.write("    <div class=\"container h-100\">\n");
      out.write("        <div class=\"row h-100 align-items-center justify-content-center\">\n");
      out.write("            <div class=\"col-12 col-md-10\">\n");
      out.write("                <div class=\"hero-content\">\n");
      out.write("                    <h2>라라랜드 같은 로맨스 영화</h2>\n");
      out.write("                    <h4>최신 로맨스 영화 보러 갈래?</h4>\n");
      out.write("                    <button type=\"submit\" class=\"btn dorne-btn\" onclick=\"location.href='/movie-dam/movie/movie_list.jsp?resultPage=1&sort=vote_count&with_genres=10749' \"><i class=\"fa fa-search pr-2\" aria-hidden=\"true\"></i> 보러가기</button>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("    </div>\n");
      out.write("</section>\n");
      out.write("<!-- ***** Welcome Area End ***** -->\n");
      out.write("\n");
      out.write("<!-- ***** Catagory Area Start ***** -->\n");
      out.write("<section class=\"dorne-catagory-area\">\n");
      out.write("    <div class=\"container\">\n");
      out.write("        <div class=\"row\">\n");
      out.write("            <div class=\"col-12\">\n");
      out.write("                <div class=\"all-catagories\">\n");
      out.write("                    <div class=\"row\">\n");
      out.write("                        <!-- Single Catagory Area -->\n");
      out.write("                        <div class=\"col-12 col-sm-6 col-md\">\n");
      out.write("                            <div class=\"single-catagory-area wow fadeInUpBig\" data-wow-delay=\"0.2s\">\n");
      out.write("                                <div class=\"catagory-content\">\n");
      out.write("                                    <img src=\"/movie-dam/assets/img/core-img/icon-5.png\" alt=\"\">\n");
      out.write("                                    <a href=\"/movie-dam/movie/movie_list.jsp\">\n");
      out.write("                                        <h6>Movies</h6>\n");
      out.write("                                    </a>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                        <!-- Single Catagory Area -->\n");
      out.write("                        <div class=\"col-12 col-sm-6 col-md\">\n");
      out.write("                            <div class=\"single-catagory-area wow fadeInUpBig\" data-wow-delay=\"0.4s\">\n");
      out.write("                                <div class=\"catagory-content\">\n");
      out.write("                                    <img src=\"/movie-dam/assets/img/core-img/icon-2.png\" alt=\"\">\n");
      out.write("                                    <a href=\"/movie-dam/board/cinema_restaurant.jsp\">\n");
      out.write("                                        <h6>Restaurants</h6>\n");
      out.write("                                    </a>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                        <!-- Single Catagory Area -->\n");
      out.write("                        <div class=\"col-12 col-sm-6 col-md\">\n");
      out.write("                            <div class=\"single-catagory-area wow fadeInUpBig\" data-wow-delay=\"0.6s\">\n");
      out.write("                                <div class=\"catagory-content\">\n");
      out.write("                                    <img src=\"/movie-dam/assets/img/core-img/icon-3.png\" alt=\"\">\n");
      out.write("                                    <a href=\"/movie-dam/board/free_board.jsp?category=all\">\n");
      out.write("                                        <h6>Free Board</h6>\n");
      out.write("                                    </a>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                        <!-- Single Catagory Area -->\n");
      out.write("                        <div class=\"col-12 col-sm-6 col-md\">\n");
      out.write("                            <div class=\"single-catagory-area wow fadeInUpBig\" data-wow-delay=\"0.8s\">\n");
      out.write("                                <div class=\"catagory-content\">\n");
      out.write("                                    <img src=\"/movie-dam/assets/img/core-img/icon-4.png\" alt=\"\">\n");
      out.write("                                    <a href=\"/movie-dam/debate/debate_chanban.jsp\">\n");
      out.write("                                        <h6>Debate [Pro-Con]</h6>\n");
      out.write("                                    </a>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                        <!-- Single Catagory Area -->\n");
      out.write("                        <div class=\"col-12 col-md\">\n");
      out.write("                            <div class=\"single-catagory-area wow fadeInUpBig\" data-wow-delay=\"1s\">\n");
      out.write("                                <div class=\"catagory-content\">\n");
      out.write("                                    <img src=\"/movie-dam/assets/img/core-img/icon-1.png\" alt=\"\">\n");
      out.write("                                    <a href=\"/movie-dam/debate/debate_battle.jsp\">\n");
      out.write("                                        <h6>Debate [Battle]</h6>\n");
      out.write("                                    </a>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</section>\n");
      out.write("<!-- ***** Catagory Area End ***** -->\n");
      out.write("\n");
      out.write("<!-- ***** About Area Start ***** -->\n");
      out.write("<section class=\"dorne-about-area section-padding-0-100\">\n");
      out.write("    <div class=\"container\">\n");
      out.write("        <div class=\"row\">\n");
      out.write("            <div class=\"col-12\">\n");
      out.write("                <div class=\"about-content text-center\">\n");
      out.write("                    <h2>Discover your city with <br><span>Dorne</span></h2>\n");
      out.write("                    <p>Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Fusce quis tempus elit. Sed efficitur tortor neque, vitae aliquet urna varius sit amet. Ut rhoncus, nunc nec tincidunt volutpat, ex libero.</p>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</section>\n");
      out.write("<!-- ***** About Area End ***** -->\n");
      out.write("\n");
      out.write("<!-- ***** Editor Pick Area Start ***** -->\n");
      out.write("<section class=\"dorne-editors-pick-area bg-img bg-overlay-9 section-padding-100\" style=\"background-image: url(/movie-dam/assets/img/bg-img/hero-2.jpg);\">\n");
      out.write("    <div class=\"container\">\n");
      out.write("        <div class=\"row\">\n");
      out.write("            <div class=\"col-12\">\n");
      out.write("                <div class=\"section-heading text-center\">\n");
      out.write("                    <span></span>\n");
      out.write("                    <h4>BOX OFFICE</h4>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <div class=\"row\">\n");
      out.write("            <div class=\"col-12 col-lg-6\">\n");
      out.write("                <div class=\"single-editors-pick-area wow fadeInUp\" data-wow-delay=\"0.2s\">\n");
      out.write("                    <img src=\"/movie-dam/assets/img/bg-img/rank1.jpg\" alt=\"\">\n");
      out.write("                    <div class=\"editors-pick-info\">\n");
      out.write("                        <div class=\"places-total-destinations d-flex\">\n");
      out.write("                            <a href=\"#\">Rank 1</a>\n");
      out.write("\t                        <div class=\"add-more\">\n");
      out.write("\t                            <a href=\"#\">+</a>\n");
      out.write("\t                        </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"col-12 col-lg-6\">\n");
      out.write("                <div class=\"single-editors-pick-area wow fadeInUp\" data-wow-delay=\"0.4s\">\n");
      out.write("                    <img src=\"/movie-dam/assets/img/bg-img/rank2.jpg\" alt=\"\">\n");
      out.write("                    <div class=\"editors-pick-info\">\n");
      out.write("                        <div class=\"places-total-destinations d-flex\">\n");
      out.write("                            <a href=\"#\">Rank 2</a>\n");
      out.write("\t                        <div class=\"add-more\">\n");
      out.write("\t                            <a href=\"http://localhost:8090/movie-dam/movie/movie_detail.jsp?id=544627\">+</a>\n");
      out.write("\t                        </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"single-editors-pick-area wow fadeInUp\" data-wow-delay=\"0.6s\">\n");
      out.write("                    <img src=\"/movie-dam/assets/img/bg-img/rank3.jpg\" alt=\"\">\n");
      out.write("                    <div class=\"editors-pick-info\">\n");
      out.write("                        <div class=\"places-total-destinations d-flex\">\n");
      out.write("                            <a href=\"#\">Rank 3</a>\n");
      out.write("\t                        <div class=\"add-more\">\n");
      out.write("\t                            <a href=\"http://localhost:8090/movie-dam/movie/movie_detail.jsp?id=335983\">+</a>\n");
      out.write("\t                        </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</section>\n");
      out.write("<!-- ***** Editor Pick Area End ***** -->\n");
      out.write("\n");
      out.write("<!-- ***** Features Destinations Area Start ***** -->\n");
      out.write("<section class=\"dorne-features-destinations-area\">\n");
      out.write("    <div class=\"container-fluid\">\n");
      out.write("        <div class=\"row\">\n");
      out.write("            <div class=\"col-12\">\n");
      out.write("                <div class=\"section-heading dark text-center\">\n");
      out.write("                    <span></span>\n");
      out.write("                    <h4>Featured destinations</h4>\n");
      out.write("                    <p>Editor’s pick</p>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <div class=\"row\">\n");
      out.write("            <div class=\"col-12\">\n");
      out.write("                <div class=\"features-slides owl-carousel\">\n");
      out.write("                    <!-- Single Features Area -->\n");
      out.write("                    <div class=\"single-features-area\">\n");
      out.write("                        <img src=\"/movie-dam/assets/img/bg-img/feature-1.jpg\" alt=\"\">\n");
      out.write("                        <!-- Price -->\n");
      out.write("                        <div class=\"price-start\">\n");
      out.write("                            <p>FROM $59/night</p>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"feature-content d-flex align-items-center justify-content-between\">\n");
      out.write("                            <div class=\"feature-title\">\n");
      out.write("                                <h5>Ibiza</h5>\n");
      out.write("                                <p>Party</p>\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"feature-favourite\">\n");
      out.write("                                <a href=\"#\"><i class=\"fa fa-heart-o\" aria-hidden=\"true\"></i></a>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    <!-- Single Features Area -->\n");
      out.write("                    <div class=\"single-features-area\">\n");
      out.write("                        <img src=\"/movie-dam/assets/img/bg-img/feature-2.jpg\" alt=\"\">\n");
      out.write("                        <!-- Price -->\n");
      out.write("                        <div class=\"price-start\">\n");
      out.write("                            <p>FROM $59/night</p>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"feature-content d-flex align-items-center justify-content-between\">\n");
      out.write("                            <div class=\"feature-title\">\n");
      out.write("                                <h5>Paris</h5>\n");
      out.write("                                <p>Luxury</p>\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"feature-favourite\">\n");
      out.write("                                <a href=\"#\"><i class=\"fa fa-heart-o\" aria-hidden=\"true\"></i></a>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    <!-- Single Features Area -->\n");
      out.write("                    <div class=\"single-features-area\">\n");
      out.write("                        <img src=\"/movie-dam/assets/img/bg-img/feature-3.jpg\" alt=\"\">\n");
      out.write("                        <!-- Price -->\n");
      out.write("                        <div class=\"price-start\">\n");
      out.write("                            <p>FROM $59/night</p>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"feature-content d-flex align-items-center justify-content-between\">\n");
      out.write("                            <div class=\"feature-title\">\n");
      out.write("                                <h5>Lake Como</h5>\n");
      out.write("                                <p>Spectacular</p>\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"feature-favourite\">\n");
      out.write("                                <a href=\"#\"><i class=\"fa fa-heart-o\" aria-hidden=\"true\"></i></a>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    <!-- Single Features Area -->\n");
      out.write("                    <div class=\"single-features-area\">\n");
      out.write("                        <img src=\"/movie-dam/assets/img/bg-img/feature-4.jpg\" alt=\"\">\n");
      out.write("                        <!-- Price -->\n");
      out.write("                        <div class=\"price-start\">\n");
      out.write("                            <p>FROM $59/night</p>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"feature-content d-flex align-items-center justify-content-between\">\n");
      out.write("                            <div class=\"feature-title\">\n");
      out.write("                                <h5>Greece</h5>\n");
      out.write("                                <p>Sunny</p>\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"feature-favourite\">\n");
      out.write("                                <a href=\"#\"><i class=\"fa fa-heart-o\" aria-hidden=\"true\"></i></a>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    <!-- Single Features Area -->\n");
      out.write("                    <div class=\"single-features-area\">\n");
      out.write("                        <img src=\"/movie-dam/assets/img/bg-img/feature-5.jpg\" alt=\"\">\n");
      out.write("                        <!-- Price -->\n");
      out.write("                        <div class=\"price-start\">\n");
      out.write("                            <p>FROM $59/night</p>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"feature-content d-flex align-items-center justify-content-between\">\n");
      out.write("                            <div class=\"feature-title\">\n");
      out.write("                                <h5>Norway</h5>\n");
      out.write("                                <p>All Year round</p>\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"feature-favourite\">\n");
      out.write("                                <a href=\"#\"><i class=\"fa fa-heart-o\" aria-hidden=\"true\"></i></a>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</section>\n");
      out.write("<!-- ***** Features Destinations Area End ***** -->\n");
      out.write("\n");
      out.write("<!-- ***** Features Restaurant Area Start ***** -->\n");
      out.write("<section class=\"dorne-features-restaurant-area bg-default\">\n");
      out.write("    <div class=\"container-fluid\">\n");
      out.write("        <div class=\"row\">\n");
      out.write("            <div class=\"col-12\">\n");
      out.write("                <div class=\"section-heading text-center\">\n");
      out.write("                    <span></span>\n");
      out.write("                    <h4>Featured Restaurants</h4>\n");
      out.write("                    <p>Editor’s pick</p>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <div class=\"row\">\n");
      out.write("            <div class=\"col-12\">\n");
      out.write("                <div class=\"features-slides owl-carousel\">\n");
      out.write("                    <!-- Single Features Area -->\n");
      out.write("                    <div class=\"single-features-area\">\n");
      out.write("                        <img src=\"/movie-dam/assets/img/bg-img/feature-6.jpg\" alt=\"\">\n");
      out.write("                        <!-- Rating & Map Area -->\n");
      out.write("                        <div class=\"ratings-map-area d-flex\">\n");
      out.write("                            <a href=\"#\">8.5</a>\n");
      out.write("                            <a href=\"#\"><img src=\"/movie-dam/assets/img/core-img/map.png\" alt=\"\"></a>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"feature-content d-flex align-items-center justify-content-between\">\n");
      out.write("                            <div class=\"feature-title\">\n");
      out.write("                                <h5>Martha’s bar</h5>\n");
      out.write("                                <p>Manhathan</p>\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"feature-favourite\">\n");
      out.write("                                <a href=\"#\"><i class=\"fa fa-heart-o\" aria-hidden=\"true\"></i></a>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    <!-- Single Features Area -->\n");
      out.write("                    <div class=\"single-features-area\">\n");
      out.write("                        <img src=\"/movie-dam/assets/img/bg-img/feature-7.jpg\" alt=\"\">\n");
      out.write("                        <!-- Rating & Map Area -->\n");
      out.write("                        <div class=\"ratings-map-area d-flex\">\n");
      out.write("                            <a href=\"#\">9.5</a>\n");
      out.write("                            <a href=\"#\"><img src=\"/movie-dam/assets/img/core-img/map.png\" alt=\"\"></a>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"feature-content d-flex align-items-center justify-content-between\">\n");
      out.write("                            <div class=\"feature-title\">\n");
      out.write("                                <h5>Delux Restaurant</h5>\n");
      out.write("                                <p>Paris</p>\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"feature-favourite\">\n");
      out.write("                                <a href=\"#\"><i class=\"fa fa-heart-o\" aria-hidden=\"true\"></i></a>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    <!-- Single Features Area -->\n");
      out.write("                    <div class=\"single-features-area\">\n");
      out.write("                        <img src=\"/movie-dam/assets/img/bg-img/feature-8.jpg\" alt=\"\">\n");
      out.write("                        <!-- Rating & Map Area -->\n");
      out.write("                        <div class=\"ratings-map-area d-flex\">\n");
      out.write("                            <a href=\"#\">8.2</a>\n");
      out.write("                            <a href=\"#\"><img src=\"/movie-dam/assets/img/core-img/map.png\" alt=\"\"></a>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"feature-content d-flex align-items-center justify-content-between\">\n");
      out.write("                            <div class=\"feature-title\">\n");
      out.write("                                <h5>Jim’s corner Pub</h5>\n");
      out.write("                                <p>Madrid</p>\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"feature-favourite\">\n");
      out.write("                                <a href=\"#\"><i class=\"fa fa-heart-o\" aria-hidden=\"true\"></i></a>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    <!-- Single Features Area -->\n");
      out.write("                    <div class=\"single-features-area\">\n");
      out.write("                        <img src=\"/movie-dam/assets/img/bg-img/feature-9.jpg\" alt=\"\">\n");
      out.write("                        <!-- Rating & Map Area -->\n");
      out.write("                        <div class=\"ratings-map-area d-flex\">\n");
      out.write("                            <a href=\"#\">8.7</a>\n");
      out.write("                            <a href=\"#\"><img src=\"/movie-dam/assets/img/core-img/map.png\" alt=\"\"></a>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"feature-content d-flex align-items-center justify-content-between\">\n");
      out.write("                            <div class=\"feature-title\">\n");
      out.write("                                <h5>tower Risto bar</h5>\n");
      out.write("                                <p>Sydney</p>\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"feature-favourite\">\n");
      out.write("                                <a href=\"#\"><i class=\"fa fa-heart-o\" aria-hidden=\"true\"></i></a>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    <!-- Single Features Area -->\n");
      out.write("                    <div class=\"single-features-area\">\n");
      out.write("                        <img src=\"/movie-dam/assets/img/bg-img/feature-10.jpg\" alt=\"\">\n");
      out.write("                        <!-- Rating & Map Area -->\n");
      out.write("                        <div class=\"ratings-map-area d-flex\">\n");
      out.write("                            <a href=\"#\">9.8</a>\n");
      out.write("                            <a href=\"#\"><img src=\"/movie-dam/assets/img/core-img/map.png\" alt=\"\"></a>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"feature-content d-flex align-items-center justify-content-between\">\n");
      out.write("                            <div class=\"feature-title\">\n");
      out.write("                                <h5>Pizzeria venezia</h5>\n");
      out.write("                                <p>Hong Kong</p>\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"feature-favourite\">\n");
      out.write("                                <a href=\"#\"><i class=\"fa fa-heart-o\" aria-hidden=\"true\"></i></a>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</section>\n");
      out.write("<!-- ***** Features Restaurant Area End ***** -->\n");
      out.write("\n");
      out.write("<!-- ***** Features Events Area Start ***** -->\n");
      out.write("<section class=\"dorne-features-events-area bg-img bg-overlay-9 section-padding-100-50\" style=\"background-image: url(/movie-dam/assets/img/bg-img/hero-3.jpg)\">\n");
      out.write("    <div class=\"container\">  \n");
      out.write("        <div class=\"row\">\n");
      out.write("            <div class=\"col-12\">\n");
      out.write("                <div class=\"section-heading text-center\">\n");
      out.write("                    <span></span>\n");
      out.write("                    <h4>Best articles</h4>\n");
      out.write("                    <p>추천 수가 가장 많았던 게시글</p>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"row\">\n");

double delay = 0.1;
for (int i = 0 ; i < articleList.size() ; i++) {
	   ArticleDataBean article = articleList.get(i);

      out.write("\n");
      out.write("            <div class=\"col-12 col-lg-6\">\n");
      out.write("                <div class=\"single-feature-events-area d-sm-flex align-items-center wow fadeInUpBig\" data-wow-delay=\"");
      out.print(delay+0.1 );
      out.write("s\">\n");
      out.write("                    <div class=\"feature-events-thumb\">\n");
      out.write("                        <img src=\"/movie-dam/assets/img/bg-img/event-1.jpg\" alt=\"\">\n");
      out.write("                        <div class=\"date-map-area d-flex\">\n");
      out.write("                            <a href=\"#\">26 Oct</a>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"feature-events-content\">\n");
      out.write("                        <h5>");
      out.print(article.getArticle_title());
      out.write("</h5>\n");
      out.write("                        <h6>");
      out.print(article.getArticle_writer());
      out.write("</h6>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"feature-events-details-btn\">\n");
      out.write("                        <a href=\"#\">+</a>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
	} 
      out.write("\n");
      out.write("        </div>\n");
      out.write("\t</div>\t\n");
      out.write("</section>\n");
      out.write("<!-- ***** Features Events Area End ***** -->\n");
      out.write("\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/module/footer.jsp", out, false);
      out.write("\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
