/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.53
 * Generated at: 2018-10-19 12:52:11 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;

public final class movie_005fpreview_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("    \n");

	request.setCharacterEncoding("utf-8");
	String title = "시사회";

      out.write('\n');
      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/module/header.jsp" + "?" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("title", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode(String.valueOf(title ), request.getCharacterEncoding()), out, false);
      out.write('\n');
      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/module/nav.jsp", out, false);
      out.write("\n");
      out.write("\n");
      out.write("<div class=\"container\">\n");
      out.write("\t<h3>\n");
      out.write("\t\t");
      out.print(title );
      out.write("\n");
      out.write("\t\t<small class=\"text-muted\">Movie Preview</small>\n");
      out.write("\t</h3>\n");
      out.write("\t<div class=\"btn-group btn-group-toggle\" data-toggle=\"buttons\">\n");
      out.write("\t\t<label class=\"btn btn-primary\"> <input type=\"checkbox\" checked=\"checked\" autocomplete=\"off\">CGV</label> \n");
      out.write("\t\t<label class=\"btn btn-primary\"> <input type=\"checkbox\" checked=\"checked\" autocomplete=\"off\">롯데시네마</label> \n");
      out.write("\t\t<label class=\"btn btn-primary\"> <input type=\"checkbox\" checked=\"checked\" autocomplete=\"off\">메가박스</label>\n");
      out.write("\t</div>\n");
      out.write("\t<div class=\"row\">\n");
      out.write("\t\t<div class=\"col\">\n");
      out.write("\t\t\t<div class=\"card\" style=\"width: 18rem;\">\n");
      out.write("\t\t\t\t<div class=\"card-header\">\n");
      out.write("\t\t\t\t\t<span class=\"badge badge-danger\">롯데시네마</span> \n");
      out.write("\t\t\t\t\t<a href=\"http://event.lottecinema.co.kr/LCHS/Contents/Event/stage-greeting-event.aspx?EventID=401070016918152\"> '죄 많은 소녀' 관객과의 대화</a>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<a href=\"http://event.lottecinema.co.kr/LCHS/Contents/Event/stage-greeting-event.aspx?EventID=401070016918152\">\n");
      out.write("\t\t\t\t\t<img class=\"card-img-top\" src=\"http://img.cgv.co.kr/Movie/Thumbnail/Poster/000080/80986/80986_1000.jpg\" alt=\"Card image cap\">\n");
      out.write("\t\t\t\t</a>\n");
      out.write("\t\t\t\t<ul class=\"list-group list-group-flush\">\n");
      out.write("\t\t\t\t\t<li class=\"list-group-item\">일시 2018.09.15(토) 오후 3:30</li>\n");
      out.write("\t\t\t\t\t<li class=\"list-group-item\">장소 롯데시네마 월드타워 3관</li>\n");
      out.write("\t\t\t\t</ul>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div class=\"col\">\n");
      out.write("\t\t\t<div class=\"card\" style=\"width: 18rem;\">\n");
      out.write("\t\t\t\t<div class=\"card-header\">\n");
      out.write("\t\t\t\t\t<span class=\"badge badge-danger\">롯데시네마</span> \n");
      out.write("\t\t\t\t\t<a href=\"http://event.lottecinema.co.kr/LCHS/Contents/Event/preview-event.aspx?EventID=401080016918052\"> '뽀잉:슈퍼 변신의 비밀' 시사회</a>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<a href=\"http://event.lottecinema.co.kr/LCHS/Contents/Event/preview-event.aspx?EventID=401080016918052\">\n");
      out.write("\t\t\t\t\t<img class=\"card-img-top\" src=\"http://www.onlinebee.net/imgdata/onlinebee_net/201808/2018082424592319.jpg\" alt=\"Card image cap\">\n");
      out.write("\t\t\t\t</a>\n");
      out.write("\t\t\t\t<ul class=\"list-group list-group-flush\">\n");
      out.write("\t\t\t\t\t<li class=\"list-group-item\">일시 2018.09.20(목) 오후 7:00</li>\n");
      out.write("\t\t\t\t\t<li class=\"list-group-item\">장소 광명아울렛, 광복, 김포공항, 대전(백화점), 상인, 수완(아울렛), 수원, 울산(백화점), 월드타워, 율하</li>\n");
      out.write("\t\t\t\t</ul>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div class=\"col\">\n");
      out.write("\t\t\t<div class=\"card\" style=\"width: 18rem;\">\n");
      out.write("\t\t\t\t<div class=\"card-header\">\n");
      out.write("\t\t\t\t\t<span class=\"badge badge-info\">메가박스</span> \n");
      out.write("\t\t\t\t\t<a href=\"http://www.megabox.co.kr/?menuId=event-mov&p=detail&p2=6393\"> '안시성' 메가토크</a>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<a href=\"http://www.megabox.co.kr/?menuId=event-mov&p=detail&p2=6393\">\n");
      out.write("\t\t\t\t\t<img class=\"card-img-top\" src=\"http://tenasia.hankyung.com/webwp_kr/wp-content/uploads/2018/08/2018082908361030357-540x772.jpg\" alt=\"Card image cap\">\n");
      out.write("\t\t\t\t</a>\n");
      out.write("\t\t\t\t<ul class=\"list-group list-group-flush\">\n");
      out.write("\t\t\t\t\t<li class=\"list-group-item\">일시 2018.09.18(화) 오후 7:00</li>\n");
      out.write("\t\t\t\t\t<li class=\"list-group-item\">장소 메가박스 코엑스 MX</li>\n");
      out.write("\t\t\t\t</ul>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t\t\n");
      out.write("\t\t<a class=\"btn btn-sm btn-outline-secondary\" href=\"writeForm.jsp?board_id=4&article_writer=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.userid}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" role=\"button\" >글쓰기</a>\n");
      out.write("\t\t\n");
      out.write("\t</div>\n");
      out.write("\t\n");
      out.write("</div>\n");
      out.write("\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/module/footer.jsp", out, false);
      out.write("\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
